import type { AppProps } from 'next/app';
import GlobalStyles from 'styles/GlobalStyles';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { wrapper } from 'store/index';
import { ThemeProvider as EmotionThemeProvider } from '@emotion/react';
import { ThemeProvider as MuiThemeProvider } from '@mui/material';
import EmotionTheme from 'styles/theme';
import { theme as MuiTheme } from 'styles/muiTheme';
import useSWR from 'swr';
import { AUTH_USER } from '@/apis/keys';
import { authFetcher } from '@/apis/authFetcher';
import { useRouter } from 'next/router';

function MyApp({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const router = useRouter();

  const { data } = useSWR(AUTH_USER, authFetcher);

  if (data?.message === 'needResetPassword') {
    // prevent infinite routing loop
    if (router.pathname !== '/resetPassword') {
      router.replace('/resetPassword');
    }
  }

  return (
    <>
      <Head>
        <title>Getit</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MuiThemeProvider theme={MuiTheme}>
        <EmotionThemeProvider theme={EmotionTheme}>
          <GlobalStyles />
          <Provider store={store}>
            <Component {...props.pageProps} />
          </Provider>
        </EmotionThemeProvider>
      </MuiThemeProvider>
    </>
  );
}

export default MyApp;
