import type { AppProps } from 'next/app';
import GlobalStyles from 'styles/GlobalStyles';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { wrapper } from 'store/index';
import { ThemeProvider as EmotionThemeProvider } from '@emotion/react';
import { ThemeProvider as MuiThemeProvider } from '@mui/material';
import EmotionTheme from 'styles/theme';
import { theme as MuiTheme } from 'styles/muiTheme';
import CheckAuth from 'lib/auth/CheckAuth';

function MyApp({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);

  return (
    <>
      <Head>
        <title>Getit</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <EmotionThemeProvider theme={EmotionTheme}>
        <MuiThemeProvider theme={MuiTheme}>
          <GlobalStyles />
          <Provider store={store}>
            {/* <Component {...props.pageProps} />; */}
            <CheckAuth Component={Component} Props={props} />
          </Provider>
        </MuiThemeProvider>
      </EmotionThemeProvider>
    </>
  );
}

export default MyApp;
